name: teslo_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.8.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  image_picker: ^1.1.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "252829"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/icon/
    - google_fonts/montserrat_alternates/
